//
//  Workspace.swift
//  Config
//
//  Created by Kyeongmo Yang on 9/6/24.
//

import ProjectDescription

let workspace = Workspace(
    name: "Pokedex",
    projects: ["App"],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .relevant
        )
    )
)
